/*
  game.js source
  obfuscated code (ob.js) generated by https://www.obfuscator.io
*/

gameStarted = false;
dialogIsShowing = true;
tooFarDialogShown = false;
justFoundStage = false;

var fullscreenWrapper = document.getElementById("fullscreen-wrapper");
var overlayDialog = document.getElementById("overlay-dialog");

var suspiciousRock = document.getElementById("suspicious-rock");
var suspiciousRockFlipped = false;
var fire = document.getElementById("fire");


function openFullscreen() {
  if (fullscreenWrapper.requestFullscreen) {
    fullscreenWrapper.requestFullscreen();
  } else if (elem.mozRequestFullScreen) {
    fullscreenWrapper.mozRequestFullScreen();
  } else if (elem.webkitRequestFullscreen) {
    fullscreenWrapper.webkitRequestFullscreen();
  } else if (elem.msRequestFullscreen) {
    fullscreenWrapper.msRequestFullscreen();
  }
}

function isFullscreen(){
  return 1 >= outerHeight - innerHeight;
}

function showDialog(title, text) {
  if (!dialogIsShowing) {
    document.getElementById("dialog-title").innerHTML = title;
    document.getElementById("dialog-text").innerHTML = text;

    overlayDialog.style.display = "table";
    dialogIsShowing = true;
  }
}

function calcDistance(elem1, elem2) {
  e1Pos = elem1.getAttribute("position");
  if (typeof elem2 == "number") {
    var a = e1Pos.x + 2.75;
    var b = e1Pos.y;
    var c = e1Pos.z - 4.5;
  } else {
    e2Pos = elem2.getAttribute("position");
    var a = e1Pos.x - e2Pos.x;
    var b = e1Pos.y - e2Pos.y;
    var c = e1Pos.z - e2Pos.z;
  }
  return Math.sqrt(a*a + b*b + c*c);
}

function getCoords(stageFound) {
  return "<span class=\"coords\">" +
        "N 39 18."+
          (stageFound==1 ? "<b>1</b>" : "_") +
          (stageFound==3 ? "<b>23</b>" : "__") +
          " W 084 18."+
          (stageFound==2 ? "<b>4</b>" : "_") +
          (stageFound==4 ? "<b>56</b>" : "__") +
        "</span>";
}

suspiciousRock.addEventListener('click', function (evt) {
  if (!suspiciousRockFlipped) {
    suspiciousRock.emit("flip-rock");
    suspiciousRockFlipped = true;
  } else {
    suspiciousRock.emit("flip-back");
    suspiciousRockFlipped = false;
  }
});

fire.addEventListener('click', function (evt) {
  showDialog("Ahhhhhh...", "It feels nice and warm by the fire.");
});

// update compass rotation based on camera's rotation on Y axis
fullscreenWrapper.addEventListener('mousemove', e => {
  var cam = document.getElementById("camera");
  var compass = document.getElementById("compass");
  var rot = cam.getAttribute('rotation').y;

  compass.style.transform = 'rotate(' + rot + 'deg)';
  compass.style.webkitTransform = 'rotate(' + rot + 'deg)';
  compass.style.mozTransform = 'rotate(' + rot + 'deg)';
  compass.style.msTransform = 'rotate(' + rot + 'deg)';
  compass.style.oTransform = 'rotate(' + rot + 'deg)';
});

fullscreenWrapper.addEventListener('mousedown', e => {
  if(!isFullscreen()) {
    openFullscreen();
  }
  if(!gameStarted) {
    document.getElementById("overlay-intro").style.display = "none";
    gameStarted = true;
  }
  if (dialogIsShowing) {
    overlayDialog.style.display = "none";
    if (justFoundStage) {
      if (suspiciousRockFlipped) {
        suspiciousRock.emit("flip-back");
        suspiciousRockFlipped = false;
      }
      justFoundStage = false;
    }
    setTimeout(function() {
      dialogIsShowing = false;
    }, 100);
  }
});

fullscreenWrapper.addEventListener('keypress', e => {
  var dist = calcDistance(document.getElementById("rig"), 0);
  if (dist > 25 && !tooFarDialogShown) {
    showDialog("Hmmm...", "It's probably best not to stray too far from the fire. You don't want to get lost in this fog!");
    tooFarDialogShown = true;
  } else if (dist < 23) {
    tooFarDialogShown = false;
  }
});

stages = [document.getElementById("s1"), document.getElementById("s2"), document.getElementById("s3"), document.getElementById("s4")];

for(var i=0; i<4; i++) {
  stages[i].addEventListener('click', function(evt) {
    var distance = calcDistance(document.getElementById("rig"), this);
    console.log(distance);
    if (distance<3) { // if player is withing 2.5 feet of the stage, show them the clue
      stageFound = parseInt(this.id.substring(1));
      showDialog("Congratulations!", "<span>You have found stage&nbsp;"+stageFound+"!</span><br><br>Here's a piece of the final coordinates:<br>"+getCoords(stageFound));
      justFoundStage = true;
    } else {
      showDialog("Almost...", "It's out of your reach. Try getting closer.");
    }
  });
}
